/**
 * This is a block comment.
 **/
 
message Foo : Bar
{
	id(0) int8 id
	id(2) int8 id2
}

// This is a line comment.

message Spam : Foo
{
	id(3) int8 id3
	id(4)int8 id4
}

message Third
{

}